### ISSUE TITLE
Add the ability to specify an hgrc from configuration

### ISSUE THREAD

**Issue by Callek** [mozilla-releng/treescript#12]
Currently we hardcode the hgrc file in the treescript repo, and this is great for testing and some ease of deployment.

However there can be useful reasons for wanting to specify the hgrc externally, such as different server fingerprint changes, or other security/usability metrics.

We should instead allow it to be specified by a config entry.

**Comment by rahul-shiv** [comment]
Hi, I'd like to fix this bug. Please fill me in on the necessary details.

**Comment by Callek** [comment]
Basically we need to add an hgrc option here https://github.com/mozilla-releng/treescript/blob/master/treescript/script.py#L75

Then we'll want to modify https://github.com/mozilla-releng/treescript/blob/1a52704a2770f82b52afdcdf596d217897a54e1b/treescript/mercurial.py#L46 to have the context (so we can access the config) and use the hgrc from config if it exists.

Using the hgrc should throw an error (early) if it's defined in config but doesn't exist, this prevents misconfiguration.

Lastly we should add/modify tests for this, both for the build_hg_environment to be sure that we use the built in hgrc if we don't define one, that we use the config one if we do (can use a tmpdir pytest fixture to satisfy the file.exists()) and of course a test to make sure that if one doesn't exist but is defined we throw an error.

Also modify the config_example.json to suit.

... Hrm thinking more we can move the default hgrc file to get_default_config and always use the config hgrc would probably be cleaner.

I've been a bit hand wavy on some of this, but thats mostly because I didn't deep dive on it yet, but feel free to have at it, I'm also willing, of course, to help with any specific bits.

**Comment by Callek** [comment]
no worry, (I'm about to head to sleep where I am, and just wanted to make sure you saw the explanation of how to proceed here, incase you had questions). If you feel you need input before tests feel free to raise a PR, if not feel free to wait I don't mind either way.

**Comment by rahul-shiv** [comment]
Sure, I'll let you know if I have any questions. Thanks.
