### ISSUE TITLE
Add retry support

### ISSUE THREAD

**Issue by Callek** [mozilla-releng/treescript#9]
When pushing, it is entirely possible to hit push race conditions, such as another user/script pushing to the destination repository.

To solve this we should add support for retrying the commands rather than failing outright, this would be by doing all actions over again, not just a rebase. And then trying again.

There should be a max retry limit as well, so we don't spend a long time trying to push and failing.

**Comment by escapewindow** [comment]
This is fixed in the scriptworker-scripts port.
